Changed AWKPATH in shell to remove DESTDIR.  Changed e2_guide to print nothing if the EPUB has no landmarks.

diff --git a/aov-html2epub b/aov-html2epub
--- a/aov-html2epub
+++ b/aov-html2epub
@@ -182,7 +182,8 @@ work=$( mktemp )
 
 
 if ! awk -v ops=${OPS} -f ttitle.awk -- "${HTML[@]}" > $main ; then
-    echo "ttitle.awk error!" > /dev/stderr
+    echo "$0: ttitle.awk error!" > /dev/stderr
+    exit 1
 fi
 
 
